# rotary
# dom freq
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary","base_freq": 45200.09741519552,"d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 8, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1_22ndfeb/TST_rotary" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary","base_freq": 212.60314535583788,"d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 8, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1_22ndfeb/TST_rotary" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary","base_freq": 14.58091716442549,"d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 8, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1_22ndfeb/TST_rotary" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary","base_freq": 4.624022196198489,"d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 8, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1_22ndfeb/TST_rotary" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary","base_freq": 10000.0,"d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 8, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1_22ndfeb/TST_rotary" --save-true-pred True

#sinespe
# dom freq
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "sinespe","spe_freq": 0.04168, "spe_k": 12, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 8, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1_22ndfeb/TST_sine" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "sinespe","spe_freq": 0.04168, "spe_k": 8, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 8, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1_22ndfeb/TST_sine" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "sinespe","d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 8, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1_22ndfeb/TST_sine" --save-true-pred True
