# rotary seed sweep: best, default, random=5000
# best base from result/rope_k_analysis/rope_k_best_vs_default.csv

# seed 2021
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --seed 2021 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 233.29467463080783, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_seed2021/TST_rotary" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --seed 2021 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 10000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_seed2021/TST_rotary" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --seed 2021 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 5000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_seed2021/TST_rotary" --save-true-pred True

# seed 2022
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --seed 2022 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 233.29467463080783, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_seed2022/TST_rotary" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --seed 2022 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 10000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_seed2022/TST_rotary" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --seed 2022 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 5000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_seed2022/TST_rotary" --save-true-pred True

# seed 2023
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --seed 2023 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 233.29467463080783, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_seed2023/TST_rotary" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --seed 2023 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 10000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_seed2023/TST_rotary" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --seed 2023 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 5000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_seed2023/TST_rotary" --save-true-pred True

# old exploratory commands retained for reference:
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 54426.4052110945, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_22ndfeb/TST_rotary" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 22.54698477804209, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_22ndfeb/TST_rotary" --save-true-pred True

# sinespe
# dominant freq = 0.01042, reduced k sweep = default, 1, 2, 4, 7
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "sinespe", "base_freq": 2962233584.202254, "d_model": 16, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_17thmar/TST_sine" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "sinespe", "base_freq": 54426.4052110945, "d_model": 16, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_17thmar/TST_sine" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "sinespe", "base_freq": 233.29467463080783, "d_model": 16, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_17thmar/TST_sine" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "sinespe", "base_freq": 22.54698477804209, "d_model": 16, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_17thmar/TST_sine" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "sinespe", "d_model": 16, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1_17thmar/TST_sine" --save-true-pred True
