# rotary seed sweep: best, default, random=5000
# best base from result/rope_k_analysis/rope_k_best_vs_default.csv

# seed 2021
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2021 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 17237.391423477242, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar_seed2021/TST_rotary_ci64_every2" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2021 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 10000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar_seed2021/TST_rotary_ci64_every2" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2021 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 5000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar_seed2021/TST_rotary_ci64_every2" --save-true-pred True

# seed 2022
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2022 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 17237.391423477242, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar_seed2022/TST_rotary_ci64_every2" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2022 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 10000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar_seed2022/TST_rotary_ci64_every2" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2022 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 5000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar_seed2022/TST_rotary_ci64_every2" --save-true-pred True

# seed 2023
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2023 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 17237.391423477242, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar_seed2023/TST_rotary_ci64_every2" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2023 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 10000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar_seed2023/TST_rotary_ci64_every2" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2023 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 5000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar_seed2023/TST_rotary_ci64_every2" --save-true-pred True

# old exploratory commands retained for reference:
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 297127663.0861668, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar_22ndfeb/TST_rotary_ci64_every2" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 131.29124656075606, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar_22ndfeb/TST_rotary_ci64_every2" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 16.233809339931238, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar_22ndfeb/TST_rotary_ci64_every2" --save-true-pred True

# sinespe
# dominant freq = 0.01389, reduced k sweep = default, 1, 2, 4, 7
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "sinespe", "base_freq": 297127663.0861668, "d_model": 16, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 2 --num-workers 1 --timeout 60000 --save-path "Solar_17thmar/TST_sine_ci64_every2" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "sinespe", "base_freq": 17237.391423477242, "d_model": 16, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 2 --num-workers 1 --timeout 60000 --save-path "Solar_17thmar/TST_sine_ci64_every2" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "sinespe", "base_freq": 131.29124656075606, "d_model": 16, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 2 --num-workers 1 --timeout 60000 --save-path "Solar_17thmar/TST_sine_ci64_every2" --save-true-pred True
# python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "sinespe", "base_freq": 16.233809339931238, "d_model": 16, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 2 --num-workers 1 --timeout 60000 --save-path "Solar_17thmar/TST_sine_ci64_every2" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "sinespe", "d_model": 16, "n_heads": 8, "num_layers": 1, "dim_feedforward": 2048, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 2 --num-workers 1 --timeout 60000 --save-path "Solar_17thmar/TST_sine_ci64_every2" --save-true-pred True
