#!/usr/bin/env bash
set -euo pipefail

DATASET_GROUP="${1:-all}"

run_ettm1() {
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --seed 2022 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 233.29467463080783, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 1 --num-workers 1 --timeout 60000 --save-path "ETTm1_seed2022/TST_rotary" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --seed 2022 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 10000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 1 --num-workers 1 --timeout 60000 --save-path "ETTm1_seed2022/TST_rotary" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --seed 2022 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 5000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 1 --num-workers 1 --timeout 60000 --save-path "ETTm1_seed2022/TST_rotary" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --seed 2023 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 233.29467463080783, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 1 --num-workers 1 --timeout 60000 --save-path "ETTm1_seed2023/TST_rotary" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --seed 2023 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 10000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 1 --num-workers 1 --timeout 60000 --save-path "ETTm1_seed2023/TST_rotary" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --seed 2023 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 5000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 512, "dropout": 0.1, "norm": true, "seq_len": 96, "horizon": 96, "batch_size": 16, "lr": 0.0001, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 1 --num-workers 1 --timeout 60000 --save-path "ETTm1_seed2023/TST_rotary" --save-true-pred True
}

run_weather() {
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --seed 2021 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 10000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 32, "lr": 0.0005, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 2 --num-workers 1 --timeout 60000 --save-path "Weather_seed2021/TST_rotary" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --seed 2021 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 5000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 32, "lr": 0.0005, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 2 --num-workers 1 --timeout 60000 --save-path "Weather_seed2021/TST_rotary" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --seed 2022 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 131.29124656075606, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 32, "lr": 0.0005, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 2 --num-workers 1 --timeout 60000 --save-path "Weather_seed2022/TST_rotary" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --seed 2022 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 10000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 32, "lr": 0.0005, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 2 --num-workers 1 --timeout 60000 --save-path "Weather_seed2022/TST_rotary" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --seed 2022 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 5000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 32, "lr": 0.0005, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 2 --num-workers 1 --timeout 60000 --save-path "Weather_seed2022/TST_rotary" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --seed 2023 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 131.29124656075606, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 32, "lr": 0.0005, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 2 --num-workers 1 --timeout 60000 --save-path "Weather_seed2023/TST_rotary" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --seed 2023 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 10000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 32, "lr": 0.0005, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 2 --num-workers 1 --timeout 60000 --save-path "Weather_seed2023/TST_rotary" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --seed 2023 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 5000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 32, "lr": 0.0005, "num_epochs": 100, "patience": 5}' --deterministic "full" --gpus 2 --num-workers 1 --timeout 60000 --save-path "Weather_seed2023/TST_rotary" --save-true-pred True
}

run_solar() {
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2021 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 10000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 3 --num-workers 1 --timeout 60000 --save-path "Solar_seed2021/TST_rotary_ci64_every2" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2021 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 5000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 3 --num-workers 1 --timeout 60000 --save-path "Solar_seed2021/TST_rotary_ci64_every2" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2022 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 17237.391423477242, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 3 --num-workers 1 --timeout 60000 --save-path "Solar_seed2022/TST_rotary_ci64_every2" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2022 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 10000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 3 --num-workers 1 --timeout 60000 --save-path "Solar_seed2022/TST_rotary_ci64_every2" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2022 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 5000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 3 --num-workers 1 --timeout 60000 --save-path "Solar_seed2022/TST_rotary_ci64_every2" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2023 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 17237.391423477242, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 3 --num-workers 1 --timeout 60000 --save-path "Solar_seed2023/TST_rotary_ci64_every2" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2023 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 10000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 3 --num-workers 1 --timeout 60000 --save-path "Solar_seed2023/TST_rotary_ci64_every2" --save-true-pred True
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar_ci64_every2.csv" --strategy-args '{"horizon": 96}' --seed 2023 --model-name "tst.TST" --model-hyper-params '{"pos_encoding": "rotary", "base_freq": 5000.0, "d_model": 128, "n_heads": 8, "num_layers": 1, "dim_feedforward": 256, "dropout": 0.1, "norm": true, "channel_independence": true, "revin": true, "seq_len": 96, "horizon": 96, "batch_size": 4, "lr": 0.0005, "num_epochs": 100, "patience": 3}' --deterministic "full" --gpus 3 --num-workers 1 --timeout 60000 --save-path "Solar_seed2023/TST_rotary_ci64_every2" --save-true-pred True
}

case "$DATASET_GROUP" in
  ettm1) run_ettm1 ;;
  weather) run_weather ;;
  solar) run_solar ;;
  all)
    run_ettm1
    run_weather
    run_solar
    ;;
  *)
    echo "Unknown dataset group: $DATASET_GROUP" >&2
    exit 1
    ;;
esac
